name: flow2

on:
  workflow_dispatch:

jobs:
  build:
  name: Hello world
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Write a multi-line message flow 2
    run: |
      echo This demo file shows a flow 2
      echo very basic and easy-to-understand workflow.