name: Get_Solution_And_Commit

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      dynamic_branch:
        description: Select branch
        required: true
        type: dynamic_branch
        default: main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          path: main
