name: Get_Solution_Get_Branch_And_Commit

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      solution-name: 
        required: true
      dynamic_branch:
        description: Select branch
        required: true
        type: dynamic_branch
        default: main

jobs:
  build:
    runs-on: windows-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      
    steps:
      - name: Set color
        id: color-selector
        run: |
            $color='blue'
            "SELECTED_COLOR=$color" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: Write-Output "The selected color is $env:SELECTED_COLOR"
    
      # install pac
      - name: install pac
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool   
          
      - name: export solution
        run: |       
          pac auth create --applicationId ${{ secrets.APP_ID }} --clientSecret '${{ secrets.CLIENT_SECRET }}' -t '${{ secrets.TENANT_ID }}' --environment '${{ secrets.ENV }}'
          $workingFolder='${{ github.event.inputs.solution-name }}'
          $solutionName='${{ github.event.inputs.solution-name }}'
          $zipFile = ".\$solutionName\$solutionName.zip"
          
          pac solution export --name $solutionName --path .\$solutionName --overwrite
          #unpack solution
          pac solution unpack --zipfile $zipFile --folder $workingFolder --processCanvasApps
          echo "path=${{ github.workspace }}" >> $GITHUB_OUTPUT

      - name: get branch and commit id
        id: extractRepoValues
        run: |
          $folderPath='.\${{ github.event.inputs.solution-name }}\organizationsettings\dd_branchName'
          $fileName='organizationsetting.xml'
          $childNodeName='value'
          
          $xmlFilePath = Get-ChildItem -Path $folderPath -Recurse -Filter $fileName | Select-Object -ExpandProperty FullName -First 1
          [xml]$xml = Get-Content -Path $xmlFilePath
          
          # Find the node with the specified attribute value
          $node = $xml.SelectSingleNode("//value")
          
          $node.innerText
          "branch=$($node.innerText)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          
          $folderPath='.\${{ github.event.inputs.solution-name }}\organizationsettings\dd_commitReference'
          $fileName='organizationsetting.xml'
          $childNodeName='value'
          
          $xmlFilePath = Get-ChildItem -Path $folderPath -Recurse -Filter $fileName | Select-Object -ExpandProperty FullName -First 1
          [xml]$xml = Get-Content -Path $xmlFilePath
          
          # Find the node with the specified attribute value
          $node = $xml.SelectSingleNode("//value")
          
          $node.innerText
          "commitReference=$($node.innerText)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          

      - name: testOutput
        env:
          branch: ${{ steps.extractRepoValues.outputs.branch }}
        run: |
          Write-Output "The selected color is $env:branch"
          Write-Output "${{ steps.extractRepoValues.outputs.branch }}"
          Write-Output "${{ steps.extractRepoValues.outputs.commitReference }}"

      - name: Checkout branch at specific commit
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.extractRepoValues.outputs.branch }}
          path: repo

      - name: Reset to specific commit
        run: |
          cd repo
          git reset --hard ${{ steps.extractRepoValues.outputs.commitReference }}

      - name: Copy content of folder 'mySolution' into 'repo'
        run: |
          cp -r ${{ github.event.inputs.solution-name }}/* repo/          

      - name: Show changes in 'repo'
        run: |
          cd repo
          git status      
