
name: test_struct

on:   
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Greet someone
        uses: ./flow1
        with:
          who-to-greet: "everyone"
